"""
Django settings for framework project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import time
from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file before any other settings
load_dotenv(BASE_DIR / '.env')
PROJECT_UA = "AI4Video"
PROJECT_BUILT = "AI4Video built on 2026/07/07"
PROJECT_VERSION = "1.002"
PROJECT_FLAG = "AI4Video"
PROJECT_ADMIN_START_TIMESTAMP = int(time.time()) # 软件启动时间戳（秒单位）

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG defaults to False; set DJANGO_DEBUG=true in .env to enable
DEBUG = os.environ.get('DEBUG', 'False').lower() == 'true'

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')
if not SECRET_KEY:
    if DEBUG:
        # Development only: allow insecure default with warning
        import warnings
        warnings.warn(
            "DJANGO_SECRET_KEY not set. Using insecure default for development only. "
            "Set DJANGO_SECRET_KEY in .env for production.",
            UserWarning
        )
        SECRET_KEY = 'ai4video-dev-insecure-key-change-in-production'
    else:
        # Production: require proper secret key
        raise ValueError(
            "DJANGO_SECRET_KEY environment variable is required in production. "
            "Set it in your .env file or environment."
        )

# ALLOWED_HOSTS defaults to localhost; set comma-separated list in .env for production
ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost').split(',')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_ratelimit',
    'rest_framework',
    'drf_spectacular',
    'compressor',
    'app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.gzip.GZipMiddleware',  # 启用 Gzip 压缩，提升响应性能
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'app.middleware.RateLimitMiddleware',  # 请求限流
    'app.middleware.AuditMiddleware',  # 审计日志
    "app.middleware.SimpleMiddleware",  # 拦截器
]

ROOT_URLCONF = 'framework.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR,'templates')
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.csrf',
                'app.context_processors.lang_processor',
            ],
        },
    },
]

WSGI_APPLICATION = 'framework.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'ai4video.sqlite3',
        # SQLite 性能优化：见下方 connection_created 信号中的 PRAGMA 设置
        'OPTIONS': {
            'timeout': 20,  # Python 端连接超时（秒）
        },
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

#LANGUAGE_CODE = 'zh-hans'
#LANGUAGE_CODE = 'en'
#TIME_ZONE = 'UTC'
USE_I18N = True # 启用国际化
# USE_L10N = True # 启用本地化（如日期、数字格式）
USE_TZ = False
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'
LANGUAGE_CODE = 'zh-hans'
TIME_ZONE = 'Asia/Shanghai'

""" 静态资源（DEBUG=True：staticfiles 从 STATICFILES_DIRS 直接提供） """
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "static"),
)

SESSION_COOKIE_NAME = 'AI4VideoSessionID'
SESSION_EXPIRE_AT_BROWSER_CLOSE=False #会话cookie可以在用户浏览器中保持有效期  True：关闭浏览器则Cookie失效。
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# 防止暴力破解
SESSION_COOKIE_AGE=2*24*60*60   # session过期，单位（秒）2天=2*24*60*60（reduced from 7 days for security）

X_FRAME_OPTIONS = 'SAMEORIGIN'
CSRF_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_HTTPONLY = True

# 允许大JSON请求体（集群平台通过WebSocket传递base64文件，模型文件最大1000M）
DATA_UPLOAD_MAX_MEMORY_SIZE = 1073741824  # 1GB (reduced from 1.5GB for security)

# REST Framework
REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# drf-spectacular OpenAPI
SPECTACULAR_SETTINGS = {
    'TITLE': 'AI4Video API',
    'DESCRIPTION': 'AI4Video 视频分析平台 API 文档',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'SWAGGER_UI_SETTINGS': {
        'deepLinking': True,
        'persistAuthorization': True,
        'displayOperationId': True,
    },
}

# django-compressor
COMPRESS_ENABLED = True
COMPRESS_ROOT = BASE_DIR / 'static'
COMPRESS_CSS_FILTERS = ['compressor.filters.css_default.CssAbsoluteFilter']
COMPRESS_JS_FILTERS = ['compressor.filters.jsmin.JSMinFilter']
COMPRESS_OFFLINE = False  # DEBUG mode: compress on-the-fly; set True for production
STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'compressor.finders.CompressorFinder',
]

# Cache for django-ratelimit (D-09). This app runs as a single process
# (manage.py runserver/runworker), so the thread-safe LocMemCache is shared
# across all requests. Set RATELIMIT_USE_CACHE to a Redis/memcached backend
# here if deploying behind multiple WSGI workers.
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
    }
}
# LocMemCache is process-local; the ratelimit check warnings assume a
# multi-process deployment, which this single-process app does not use.
# Re-enable these checks if switching to a multi-worker WSGI server.
SILENCED_SYSTEM_CHECKS = ['django_ratelimit.E003', 'django_ratelimit.W001']

# Security
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'
